/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2015-08-03 17:34:38 UTC)
 * on 2015-08-22 at 11:13:14 UTC 
 * Modify at your own risk.
 */

package com.appspot.uplifted_plate_89814.imagecam;

/**
 * Service definition for Imagecam (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link ImagecamRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Imagecam extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.18.0-rc of the imagecam library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://uplifted-plate-89814.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "imagecam/v1/SendImage/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Imagecam(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Imagecam(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "sendimage".
   *
   * This request holds the parameters needed by the imagecam server.  After setting any optional
   * parameters, call the {@link Sendimage#execute()} method to invoke the remote operation.
   *
   * @param imageKey
   * @param number
   * @return the request
   */
  public Sendimage sendimage(java.lang.Long imageKey, java.lang.Long number) throws java.io.IOException {
    Sendimage result = new Sendimage(imageKey, number);
    initialize(result);
    return result;
  }

  public class Sendimage extends ImagecamRequest<Void> {

    private static final String REST_PATH = "{ImageKey}/{number}";

    /**
     * Create a request for the method "sendimage".
     *
     * This request holds the parameters needed by the the imagecam server.  After setting any
     * optional parameters, call the {@link Sendimage#execute()} method to invoke the remote
     * operation. <p> {@link
     * Sendimage#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param imageKey
     * @param number
     * @since 1.13
     */
    protected Sendimage(java.lang.Long imageKey, java.lang.Long number) {
      super(Imagecam.this, "POST", REST_PATH, null, Void.class);
      this.imageKey = com.google.api.client.util.Preconditions.checkNotNull(imageKey, "Required parameter imageKey must be specified.");
      this.number = com.google.api.client.util.Preconditions.checkNotNull(number, "Required parameter number must be specified.");
    }

    @Override
    public Sendimage setAlt(java.lang.String alt) {
      return (Sendimage) super.setAlt(alt);
    }

    @Override
    public Sendimage setFields(java.lang.String fields) {
      return (Sendimage) super.setFields(fields);
    }

    @Override
    public Sendimage setKey(java.lang.String key) {
      return (Sendimage) super.setKey(key);
    }

    @Override
    public Sendimage setOauthToken(java.lang.String oauthToken) {
      return (Sendimage) super.setOauthToken(oauthToken);
    }

    @Override
    public Sendimage setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (Sendimage) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public Sendimage setQuotaUser(java.lang.String quotaUser) {
      return (Sendimage) super.setQuotaUser(quotaUser);
    }

    @Override
    public Sendimage setUserIp(java.lang.String userIp) {
      return (Sendimage) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key("ImageKey")
    private java.lang.Long imageKey;

    /**

     */
    public java.lang.Long getImageKey() {
      return imageKey;
    }

    public Sendimage setImageKey(java.lang.Long imageKey) {
      this.imageKey = imageKey;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Long number;

    /**

     */
    public java.lang.Long getNumber() {
      return number;
    }

    public Sendimage setNumber(java.lang.Long number) {
      this.number = number;
      return this;
    }

    @Override
    public Sendimage set(String parameterName, Object value) {
      return (Sendimage) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Imagecam}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Imagecam}. */
    @Override
    public Imagecam build() {
      return new Imagecam(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link ImagecamRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setImagecamRequestInitializer(
        ImagecamRequestInitializer imagecamRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(imagecamRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
