/**
 * Auto-generated class
 */
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OpenAPISoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OpenAPISoap {


    /**
     * 
     * @param id
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteImgByID", action = "http://tempuri.org/DeleteImgByID")
    @WebResult(name = "DeleteImgByIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeleteImgByID", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteImgByID")
    @ResponseWrapper(localName = "DeleteImgByIDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteImgByIDResponse")
    public String deleteImgByID(
        @WebParam(name = "id", targetNamespace = "http://tempuri.org/")
        String id);

    /**
     * 
     * @param deviceName
     * @param serialnumber
     * @param password
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CheckIMEI", action = "http://tempuri.org/CheckIMEI")
    @WebResult(name = "CheckIMEIResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CheckIMEI", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckIMEI")
    @ResponseWrapper(localName = "CheckIMEIResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.CheckIMEIResponse")
    public String checkIMEI(
        @WebParam(name = "Serialnumber", targetNamespace = "http://tempuri.org/")
        String serialnumber,
        @WebParam(name = "Password", targetNamespace = "http://tempuri.org/")
        String password,
        @WebParam(name = "DeviceName", targetNamespace = "http://tempuri.org/")
        String deviceName);

    /**
     * 
     * @param cmdType
     * @param serialnumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendCommandToDeviceByCmdType", action = "http://tempuri.org/SendCommandToDeviceByCmdType")
    @WebResult(name = "SendCommandToDeviceByCmdTypeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendCommandToDeviceByCmdType", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCommandToDeviceByCmdType")
    @ResponseWrapper(localName = "SendCommandToDeviceByCmdTypeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCommandToDeviceByCmdTypeResponse")
    public String sendCommandToDeviceByCmdType(
        @WebParam(name = "Serialnumber", targetNamespace = "http://tempuri.org/")
        String serialnumber,
        @WebParam(name = "CmdType", targetNamespace = "http://tempuri.org/")
        int cmdType);

    /**
     * 
     * @param pageCount
     * @param pageNo
     * @param timeZones
     * @param serialnumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetExceptionMessageList", action = "http://tempuri.org/GetExceptionMessageList")
    @WebResult(name = "GetExceptionMessageListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetExceptionMessageList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetExceptionMessageList")
    @ResponseWrapper(localName = "GetExceptionMessageListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetExceptionMessageListResponse")
    public String getExceptionMessageList(
        @WebParam(name = "Serialnumber", targetNamespace = "http://tempuri.org/")
        String serialnumber,
        @WebParam(name = "PageNo", targetNamespace = "http://tempuri.org/")
        int pageNo,
        @WebParam(name = "PageCount", targetNamespace = "http://tempuri.org/")
        int pageCount,
        @WebParam(name = "TimeZones", targetNamespace = "http://tempuri.org/")
        String timeZones);

    /**
     * 
     * @param pageCount
     * @param pageNo
     * @param timeZones
     * @param serialnumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPhotoListByDeviceIDForThreeDays", action = "http://tempuri.org/GetPhotoListByDeviceIDForThreeDays")
    @WebResult(name = "GetPhotoListByDeviceIDForThreeDaysResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPhotoListByDeviceIDForThreeDays", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPhotoListByDeviceIDForThreeDays")
    @ResponseWrapper(localName = "GetPhotoListByDeviceIDForThreeDaysResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPhotoListByDeviceIDForThreeDaysResponse")
    public String getPhotoListByDeviceIDForThreeDays(
        @WebParam(name = "Serialnumber", targetNamespace = "http://tempuri.org/")
        String serialnumber,
        @WebParam(name = "PageNo", targetNamespace = "http://tempuri.org/")
        int pageNo,
        @WebParam(name = "PageCount", targetNamespace = "http://tempuri.org/")
        int pageCount,
        @WebParam(name = "TimeZones", targetNamespace = "http://tempuri.org/")
        String timeZones);

    /**
     * 
     * @param startTime
     * @param timeZones
     * @param endTime
     * @param serialnumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPhotoListByDeviceID", action = "http://tempuri.org/GetPhotoListByDeviceID")
    @WebResult(name = "GetPhotoListByDeviceIDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPhotoListByDeviceID", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPhotoListByDeviceID")
    @ResponseWrapper(localName = "GetPhotoListByDeviceIDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPhotoListByDeviceIDResponse")
    public String getPhotoListByDeviceID(
        @WebParam(name = "Serialnumber", targetNamespace = "http://tempuri.org/")
        String serialnumber,
        @WebParam(name = "StartTime", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar startTime,
        @WebParam(name = "EndTime", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar endTime,
        @WebParam(name = "TimeZones", targetNamespace = "http://tempuri.org/")
        String timeZones);

    /**
     * 
     * @param token
     * @param serialnumbers
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDeviceList", action = "http://tempuri.org/GetDeviceList")
    @WebResult(name = "GetDeviceListResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDeviceList", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDeviceList")
    @ResponseWrapper(localName = "GetDeviceListResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDeviceListResponse")
    public String getDeviceList(
        @WebParam(name = "Serialnumbers", targetNamespace = "http://tempuri.org/")
        String serialnumbers,
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param token
     * @param serialnumbers
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetDeviceListAndroid", action = "http://tempuri.org/GetDeviceListAndroid")
    @WebResult(name = "GetDeviceListAndroidResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetDeviceListAndroid", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDeviceListAndroid")
    @ResponseWrapper(localName = "GetDeviceListAndroidResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetDeviceListAndroidResponse")
    public String getDeviceListAndroid(
        @WebParam(name = "Serialnumbers", targetNamespace = "http://tempuri.org/")
        String serialnumbers,
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param token
     * @param imei
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "YMXRegister", action = "http://tempuri.org/YMXRegister")
    @WebResult(name = "YMXRegisterResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "YMXRegister", targetNamespace = "http://tempuri.org/", className = "org.tempuri.YMXRegister")
    @ResponseWrapper(localName = "YMXRegisterResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.YMXRegisterResponse")
    public String ymxRegister(
        @WebParam(name = "IMEI", targetNamespace = "http://tempuri.org/")
        String imei,
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param token
     * @param imei
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "YMXRegisterAndroid", action = "http://tempuri.org/YMXRegisterAndroid")
    @WebResult(name = "YMXRegisterAndroidResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "YMXRegisterAndroid", targetNamespace = "http://tempuri.org/", className = "org.tempuri.YMXRegisterAndroid")
    @ResponseWrapper(localName = "YMXRegisterAndroidResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.YMXRegisterAndroidResponse")
    public String ymxRegisterAndroid(
        @WebParam(name = "IMEI", targetNamespace = "http://tempuri.org/")
        String imei,
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param token
     * @param imei
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteYMX", action = "http://tempuri.org/DeleteYMX")
    @WebResult(name = "DeleteYMXResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeleteYMX", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteYMX")
    @ResponseWrapper(localName = "DeleteYMXResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteYMXResponse")
    public String deleteYMX(
        @WebParam(name = "IMEI", targetNamespace = "http://tempuri.org/")
        String imei,
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param token
     * @param imei
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "DeleteYMXAndroid", action = "http://tempuri.org/DeleteYMXAndroid")
    @WebResult(name = "DeleteYMXAndroidResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "DeleteYMXAndroid", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteYMXAndroid")
    @ResponseWrapper(localName = "DeleteYMXAndroidResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.DeleteYMXAndroidResponse")
    public String deleteYMXAndroid(
        @WebParam(name = "IMEI", targetNamespace = "http://tempuri.org/")
        String imei,
        @WebParam(name = "token", targetNamespace = "http://tempuri.org/")
        String token);

    /**
     * 
     * @param imei
     * @param size
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendImgSize", action = "http://tempuri.org/SendImgSize")
    @WebResult(name = "SendImgSizeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendImgSize", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendImgSize")
    @ResponseWrapper(localName = "SendImgSizeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendImgSizeResponse")
    public String sendImgSize(
        @WebParam(name = "IMEI", targetNamespace = "http://tempuri.org/")
        String imei,
        @WebParam(name = "size", targetNamespace = "http://tempuri.org/")
        int size);

    /**
     * 
     * @param imei
     * @param sos1
     * @param sos2
     * @param sos3
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendSOSNumber", action = "http://tempuri.org/SendSOSNumber")
    @WebResult(name = "SendSOSNumberResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendSOSNumber", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendSOSNumber")
    @ResponseWrapper(localName = "SendSOSNumberResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendSOSNumberResponse")
    public String sendSOSNumber(
        @WebParam(name = "IMEI", targetNamespace = "http://tempuri.org/")
        String imei,
        @WebParam(name = "sos1", targetNamespace = "http://tempuri.org/")
        String sos1,
        @WebParam(name = "sos2", targetNamespace = "http://tempuri.org/")
        String sos2,
        @WebParam(name = "sos3", targetNamespace = "http://tempuri.org/")
        String sos3);

    /**
     * 
     * @param imei
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ImageSize", action = "http://tempuri.org/ImageSize")
    @WebResult(name = "ImageSizeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "ImageSize", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ImageSize")
    @ResponseWrapper(localName = "ImageSizeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ImageSizeResponse")
    public String imageSize(
        @WebParam(name = "IMEI", targetNamespace = "http://tempuri.org/")
        String imei);

    /**
     * 
     * @param imei
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://tempuri.org/readSOS")
    @WebResult(name = "readSOSResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "readSOS", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReadSOS")
    @ResponseWrapper(localName = "readSOSResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ReadSOSResponse")
    public String readSOS(
        @WebParam(name = "IMEI", targetNamespace = "http://tempuri.org/")
        String imei);

    /**
     * 
     * @param startTime
     * @param timeZones
     * @param endTime
     * @param serialnumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetPhotoListByTime", action = "http://tempuri.org/GetPhotoListByTime")
    @WebResult(name = "GetPhotoListByTimeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetPhotoListByTime", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPhotoListByTime")
    @ResponseWrapper(localName = "GetPhotoListByTimeResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetPhotoListByTimeResponse")
    public String getPhotoListByTime(
        @WebParam(name = "Serialnumber", targetNamespace = "http://tempuri.org/")
        String serialnumber,
        @WebParam(name = "StartTime", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar startTime,
        @WebParam(name = "EndTime", targetNamespace = "http://tempuri.org/")
        XMLGregorianCalendar endTime,
        @WebParam(name = "TimeZones", targetNamespace = "http://tempuri.org/")
        String timeZones);

    /**
     * 
     * @param newPwd
     * @param oldPwd
     * @param imei
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdateDevicePwd", action = "http://tempuri.org/UpdateDevicePwd")
    @WebResult(name = "UpdateDevicePwdResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "UpdateDevicePwd", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateDevicePwd")
    @ResponseWrapper(localName = "UpdateDevicePwdResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.UpdateDevicePwdResponse")
    public String updateDevicePwd(
        @WebParam(name = "imei", targetNamespace = "http://tempuri.org/")
        String imei,
        @WebParam(name = "OldPwd", targetNamespace = "http://tempuri.org/")
        String oldPwd,
        @WebParam(name = "NewPwd", targetNamespace = "http://tempuri.org/")
        String newPwd);

    /**
     * 
     * @param imei
     * @param cmdType
     * @param cmdValue
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "SendCommandSummerByLD", action = "http://tempuri.org/SendCommandSummerByLD")
    @WebResult(name = "SendCommandSummerByLDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SendCommandSummerByLD", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCommandSummerByLD")
    @ResponseWrapper(localName = "SendCommandSummerByLDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendCommandSummerByLDResponse")
    public String sendCommandSummerByLD(
        @WebParam(name = "IMEI", targetNamespace = "http://tempuri.org/")
        String imei,
        @WebParam(name = "CmdType", targetNamespace = "http://tempuri.org/")
        String cmdType,
        @WebParam(name = "CmdValue", targetNamespace = "http://tempuri.org/")
        String cmdValue);

    /**
     * 
     * @param sn
     * @param cmdType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetCommandSummerByLD", action = "http://tempuri.org/GetCommandSummerByLD")
    @WebResult(name = "GetCommandSummerByLDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "GetCommandSummerByLD", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCommandSummerByLD")
    @ResponseWrapper(localName = "GetCommandSummerByLDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.GetCommandSummerByLDResponse")
    public String getCommandSummerByLD(
        @WebParam(name = "SN", targetNamespace = "http://tempuri.org/")
        String sn,
        @WebParam(name = "CmdType", targetNamespace = "http://tempuri.org/")
        String cmdType);

}
