/**
 * Auto-generated class
 */
package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "OpenAPI", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://www.aneasycam.net/OpenAPI.asmx?WSDL")
public class OpenAPI
    extends Service
{

    private final static URL OPENAPI_WSDL_LOCATION;
    private final static WebServiceException OPENAPI_EXCEPTION;
    private final static QName OPENAPI_QNAME = new QName("http://tempuri.org/", "OpenAPI");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.aneasycam.net/OpenAPI.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        OPENAPI_WSDL_LOCATION = url;
        OPENAPI_EXCEPTION = e;
    }

    public OpenAPI() {
        super(__getWsdlLocation(), OPENAPI_QNAME);
    }

    public OpenAPI(WebServiceFeature... features) {
        super(__getWsdlLocation(), OPENAPI_QNAME, features);
    }

    public OpenAPI(URL wsdlLocation) {
        super(wsdlLocation, OPENAPI_QNAME);
    }

    public OpenAPI(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, OPENAPI_QNAME, features);
    }

    public OpenAPI(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OpenAPI(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns OpenAPISoap
     */
    @WebEndpoint(name = "OpenAPISoap")
    public OpenAPISoap getOpenAPISoap() {
        return super.getPort(new QName("http://tempuri.org/", "OpenAPISoap"), OpenAPISoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OpenAPISoap
     */
    @WebEndpoint(name = "OpenAPISoap")
    public OpenAPISoap getOpenAPISoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "OpenAPISoap"), OpenAPISoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (OPENAPI_EXCEPTION!= null) {
            throw OPENAPI_EXCEPTION;
        }
        return OPENAPI_WSDL_LOCATION;
    }

}
